FROM ruby:2.7.0

RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update -qq && apt-get install -y yarn

# Setting up the environment
ARG RACK_ENV
ARG RAILS_ENV
ENV RAILS_ENV=$RAILS_ENV
ENV RACK_ENV=$RACK_ENV

RUN mkdir /feeder_app 
WORKDIR /feeder_app 

COPY Gemfile /feeder_app/Gemfile
RUN bundle install

COPY package.json /feeder_app/package.json
COPY yarn.lock /feeder_app/yarn.lock
RUN yarn install

COPY . /feeder_app