development:
  adapter: postgresql
  encoding: unicode
  host: db
  database: myapp_development
  user: user
  password: password
  pool: 5
  port: 5432

test:
  adapter: postgresql
  url: <%= Rails.application.credentials.database_url %>

production:
  adapter: postgresql
  url: <%= Rails.application.credentials.database_url %>
